package de.wasiakgruppe.ann.abstraction.domain

import android.content.Context
import android.support.annotation.StringRes
import de.wasiakgruppe.ann.abstraction.R

enum class MedicalSpeciality(@StringRes val stringId: Int) {
    ALLERGOLOGY(R.string.allergology),
    ANAESTHETICS(R.string.anaesthetics),
    ANGIOLOGY(R.string.angiology),
    AUDIOLOGY_AND_PHONIATRICS(R.string.audiology_and_phoniatrics),
    CARDIOLOGY(R.string.cardiology),
    CHILD_AND_YOUTH_PSYCHIATRY(R.string.child_and_youth_psychiatry),
    CHILD_PSYCHOLOGY(R.string.child_psychology),
    CLINICAL_NEUROPHYSIOLOGY(R.string.clinical_neuropsychology),
    CRANIOFACIAL_SURGERY(R.string.craniofacial_surgery),
    DENTAL_ORAL_FACIAL_SURGERY(R.string.dental_oral_facial_surgery),
    DERMATO_VENEROLOGY(R.string.dermato_venerology),
    DERMATOLOGY(R.string.dermatology),
    DIABETOLOGY(R.string.diabetology),
    ENDOCRINOLOGY(R.string.endocrinology),
    EPIDEMIOLOGY(R.string.epidemiology),
    FAMILY_MEDICINE(R.string.family_medicine),
    GASTRO_ENTEROLOGIC_SURGERY(R.string.gastro_enterologic_surgery),
    GASTROENTEROLOGY(R.string.gastroenterology),
    GENERAL_PRACTICE(R.string.general_practice),
    GENERAL_SURGERY(R.string.general_surgery),
    GENETICS(R.string.genetics),
    GERIATRICS(R.string.geriatrics),
    GYNECOLOGY(R.string.gynecology),
    HEART_SURGERY(R.string.heart_surgery),
    HEMATOLOGY(R.string.hematology),
    IMMUNOLOGY(R.string.immunology),
    INFANT_UROLOGY(R.string.infant_urology),
    INFECTIOUS_DISEASES(R.string.infectious_diseases),
    INTERNAL_MEDICINE(R.string.internal_medicine),
    MAXILLO_FACIAL_SURGERY(R.string.maxillo_facial_surgery),
    NEPHROLOGY(R.string.nephrology),
    NEURO_PSYCHIATRY(R.string.neuro_psychiatry),
    NEUROLOGY(R.string.neurology),
    NEUROPHYSIOLOGY(R.string.neurophysiology),
    NEUROSURGERY(R.string.neurosurgery),
    OBSTETRICS_AND_GYNECOLOGY(R.string.obstetrics_and_gynecology),
    OCCUPATIONAL_MEDICINE(R.string.occupational_medicine),
    ONCOLOGICAL_GYNECOLOGY(R.string.oncological_gynecology),
    ONCOLOGIST_SURGERY(R.string.oncologist_surgery),
    ONCOLOGY(R.string.oncology),
    OPHTHALMOLOGY(R.string.ophthalmology),
    ORTHODONTICS(R.string.orthodontics),
    ORTHOPAEDICS(R.string.orthopaedics),
    OTORHINOLARYNGOLOGY(R.string.otorhinolaryngology),
    PAEDIATRIC_SURGERY(R.string.paediatric_surgery),
    PAEDIATRICS(R.string.paediatrics),
    PHYSICAL_MEDICINE_AND_REHABILITATION(R.string.physical_medicine_and_rehabilitation),
    PLASTIC_SURGERY(R.string.plastic_surgery),
    PODIATRIC_SURGERY(R.string.podiatric_surgery),
    PROSTHETICS(R.string.prosthetics),
    PSYCHIATRY(R.string.psychiatry),
    PSYCHOLOGY(R.string.psychology),
    PULMONOLOGY(R.string.pulmonology),
    RADIOLOGY(R.string.radiology),
    RHEUMATOLOGY(R.string.rheumatology),
    SEXOLOGY(R.string.sexology),
    SPORTS_MEDICINE(R.string.sports_medicine),
    STOMATOLOGY(R.string.stomatology),
    THORACIC_SURGERY(R.string.thoracic_surgery),
    UROLOGY(R.string.urology),
    VASCULAR_SURGERY(R.string.vascular_surgery)
}

fun MedicalSpeciality.getName(context: Context) = context.getString(stringId)